### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by VolkerStolz** [liflab/cornipickle-android-probe#1]
Hi, just tried compiling it, but:

Sonde vs$ ANDROID_HOME=/Users/vs/Library/Android/sdk gradle assembleDebug

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > com.android.build.gradle.tasks.factory.AndroidJavaCompile.setDependencyCacheDir(Ljava/io/File;)V

```

with tracing on:

```
...
Parsing /Users/vs/Library/Android/sdk/extras/android/m2repository/package.xml
file or directory '/Users/vs/tmp/dat153/cornipickle-sonde-mobile/Sonde/app/libs', not found
file or directory '/Users/vs/tmp/dat153/cornipickle-sonde-mobile/Sonde/app/libs', not found
file or directory '/Users/vs/tmp/dat153/cornipickle-sonde-mobile/Sonde/app/libs', not found
file or directory '/Users/vs/tmp/dat153/cornipickle-sonde-mobile/Sonde/app/libs', not found


FAILURE: Build failed with an exception.
```

Maybe there's some instruction missing in the readme on how to add the Cornipickle jar?

**Comment by chafdev** [comment]
Please make sure you have the Android Support Repository installed  and  check the [Gradle configuration](https://gradle.org/install/). Thanks

**Comment by VolkerStolz** [comment]
The following has worked: load the project into Android Studio, and click through a handful of build-warnings related to older versions and have them switched to newer versions automatically. The original gradle error above is pretty useless...
